server:
  port: 8080

shareit-server:
  url: ${SERVER_URL:http://localhost:9090}

logging:
  level:
    ru.practicum.shareit: DEBUG
    org.apache.http: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG